### PR TITLE
Register plugin in about page

### PR DESCRIPTION
**Pull request by attachmentgenie**
Currently this plugin doesnt register in the plugin section of the about page. 
In order to fix this i have merged the current gemspec file and the latest one from the foreman_plugin_template repository. 
I have verified the change using a development setup following http://theforeman.org/contribute.html and http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin

### CODE REVIEW

**Comment by ohadlevy** [comment]
TBH: I'm not sure i understand why this solves the issue? I thought that it was actually fixed in 289e53e35 but we simply didnt release a new version.

**Comment by ohadlevy** [comment]
regardless, your fixes are welcomed, if you can just reword your commit message (e.g. update gemspec to align with sample plugin)

**Comment by ohadlevy** [comment]
I went ahead and modified your patch text, merged as 36e1b18d - thanks! I've also fixed all the rubocop warnings in bcc406f (since we've added rubocop to the gemspec).

**Comment by attachmentgenie** [comment]
so when will this plugin be released? 1.14 still only packages th 0.0.3 release

**Comment by ohadlevy** [comment]
@attachmentgenie I've just tagged and released a new version - thanks for the reminder.

**Comment by attachmentgenie** [comment]
:+1:

**Comment by attachmentgenie** [comment]
the nightly builds still only show the 0.0.3 release, when will the 0.0.5 release be available as a rpm?

**Comment by attachmentgenie** [comment]
managed to create the pull request for the deb but working trough test building the rpm

**Pull request closed without merging**
