### PR TITLE
Implement Cache session store by swapping out AR

### PR DESCRIPTION
**Pull request by iwalmsley**
Bug #20457 - foreman_memcache is not compatible with 1.16 (Foreman #10982).  Swap out ActiveRecordStore (the default Foreman session store middleware) instead of setting CacheStore explicitly.

### CODE REVIEW

**Comment by iwalmsley** [comment]
I'm not sure this is the best approach to be honest. As there is middleware defined in Foreman depending on the location of ActiveRecordStore, it can no longer be simply replaced without changing core code.

**Comment by matonb** [comment]
https://projects.theforeman.org/issues/20457

Any progress on this?

**Comment by schlitzered** [comment]
i was also hit by this issue after migrating to 1.16.1 from 1.16.0. it would be nice if this could get merged

**Comment by alexjfisher** [comment]
@matonb Have you been able to test this PR?

**Comment by jadestorm** [comment]
fwiw I can vouch for it working.  I'm using the patch on my own setup.

**Comment by timogoebel** [comment]
Thanks, guys and sorry for the long turnaround. I'm taking ownership of this issue. I just want to verify a few things, but this PR does look like good solution.
I'll take care of merging this and releasing a new version.

**Comment by timogoebel** [comment]
Ok, guys. I checked this one out.

If I see it correctly, this issue is only relevant for Foreman 1.16, right?
It will work again with Foreman >= 1.17.

Can we add a guard for this to the code?
Something like:

```ruby
if Gem::Version.new(Foreman::Version.new.to_s) >= Gem::Version.new('1.16.0') && Gem::Version.new(Foreman::Version.new.to_s) < Gem::Version.new('1.17.0')
  app.config.middleware.swap ActionDispatch::Session::ActiveRecordStore, ActionDispatch::Session::CacheStore
else
  app.config.session_store ActionDispatch::Session::CacheStore
end
```

That will just change the behaviour for 1.16 and might break SessionSafeLogging there. But I guess we can live with that for one core version. We should also update the README to let users know that it's recommended to not use Foreman 1.16 with this plugin.

@iwalmsley: Would you mind updating the PR? Thanks.

**Comment by timogoebel** [comment]
@iwalmsley: That's odd, I can only reproduce this on `1.16-stable`. Starting with `1.17-stable` rails starts up just fine in my env. Am I missing something?

**Comment by jadestorm** [comment]
Interesting -- I am indeed on 1.17 -- I was using a different patch (to foreman's own code) in 1.16.

**Comment by jadestorm** [comment]
To follow up on that comment -- the issue started in 1.16, but @iwalmsley 's patch was not available at the time.  In upgrading to 1.17, I switch to this patch and it's been working great.  I must admit I did not actually test the plugin without @iwalmsley 's patch under 1.17.  (just relaying my experience for data  lol)

**Comment by timogoebel** [comment]
> Am I missing something?

I actually did miss something: The memcache middleware did not load at all.

I'm currently working on a fix.

**Comment by timogoebel** [comment]
Ok, everyone:

I'd propose these changes on top of this patch:

```diff
diff --git a/lib/foreman_memcache.rb b/lib/foreman_memcache.rb
index bb6d2f9..d160183 100644
--- a/lib/foreman_memcache.rb
+++ b/lib/foreman_memcache.rb
@@ -11,11 +11,13 @@ module ForemanMemcache
       app.config.cache_store = args
     end

-    initializer 'setup_memcache', :after => :load_config_initializers do |app|
-      # reuse cache store for sessions
+    initializer 'setup_memcache', :before => :build_middleware_stack do |app|
       app.config.middleware.swap ActionDispatch::Session::ActiveRecordStore, ActionDispatch::Session::CacheStore
-      # register plugin in Foreman
+    end
+
+    initializer 'foreman_memcache.register_plugin', :before => :finisher_hook do |_app|
       Foreman::Plugin.register :foreman_memcache do
+        requires_foreman '>= 1.16'
       end
     end
   end
```

Please let me know if that works for you then we can update and merge the PR and release a new version. :-)

To see the middleware stack, just use `bundle exec rake middleware` or `foreman-rake middleware`

**Comment by iwalmsley** [comment]
@timogoebel Excellent thank you - tested on develop and working fine for me. Rebased with your proposed changes.

**Comment by jadestorm** [comment]
Awesome, thanks y'all!

**Comment by timogoebel** [comment]
I just released 0.1.0 to rubygems and filed a PR for rpm packaging: https://github.com/theforeman/foreman-packaging/pull/2434

Thanks again to everyone involved!

**Pull request merged**
